{% set name = "httpx-sse" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5bb6a2771a51e6c7a5f5c645e40b8a5f57d8de708f46cb5f3868043c3c18124e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - httpx

test:
  imports:
    - httpx_sse
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Consume Server-Sent Event (SSE) messages with HTTPX.
  home: https://github.com/florimondmanca/httpx-sse
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
